version: '3.9'
services:
  backend:
    image: golang:1.21.6
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
